### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by elkarto** [benlbrm/ha-hottoh-component#2]
![image](https://user-images.githubusercontent.com/36958524/143683404-89efaba7-ef8c-4c25-a328-2bd04acc92b6.png)

### Getting this error with last versions. Both 0.0.7 and 0.0.6. ###

"The configuration flow could not be loaded."

_Originally posted by @elkarto in https://github.com/benlbrm/hottohpy/issues/1#issuecomment-980619347_

### This is all that I did: ###

- Replace all files in custom component folder with 0.0.6 version
- Restart HA

After that, the integration appeared as "not reloaded" and the entities of the previous version appeared as "not available". For a long time. 

- I tried to remove the integration from the GUI in order to add it again. But when I click Remove nothing was happening. 
- I removed all the files inside the custom component folder.
- I restarted HA.
- After restart, the integration still appeared, so I removed it from the GUI, now it worked.
- I restarted HA again.
- I copied all files again in the custom component folder.
- Restarted HA
- Now I tried to add the integration and the error I told you was shown.
- Restart again.
- Try again.
- Remove files.
- Restart.
- Copy 0.0.7 files.
- Restart.
- Add the integration.... Same error.

Between multiple retries I've checked with pip if it was installing the correct version of hottohpy library, and yes.
Also tried removing hottohpy and installing it again. Same result.

_Originally posted by @elkarto in https://github.com/benlbrm/hottohpy/issues/1#issuecomment-980755349_

### These are the log entries: ###

- First one (before trying to add the integration)

```
Logger: homeassistant
Source: custom_components/hottoh/__init__.py:199
Integration: HottoH (documentation)
First occurred: 01:10:30 (1 occurrences)
Last logged: 01:10:30

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/hottoh/__init__.py", line 199, in <module>
    class HottohEntity(Entity):
NameError: name 'Entity' is not defined
```

- Second one (when I try to add the integration)

```
Logger: aiohttp.server
Source: custom_components/hottoh/__init__.py:199
Integration: HottoH (documentation)
First occurred: 01:12:47 (1 occurrences)
Last logged: 01:12:47

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 197, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 215, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 709, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/hottoh/__init__.py", line 199, in <module>
    class HottohEntity(Entity):
NameError: name 'Entity' is not defined

```

**Comment by elkarto** [comment]
- I have gone back to the last version that worked for me.
- I have successfully added the integration using that version.

- I have updated the files to the latest version.
- Restarted HA.

On startup I get the following error message:

```

Logger: homeassistant.setup
Source: custom_components/hottoh/__init__.py:199
Integration: HottoH (documentation)
First occurred: 02:03:39 (1 occurrences)
Last logged: 02:03:39

Setup failed for hottoh: unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 206, in _async_setup_component
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 522, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/hottoh/__init__.py", line 199, in <module>
    class HottohEntity(Entity):
NameError: name 'Entity' is not defined
```

**Comment by benlbrm** [comment]
Oup's got it, I forget to commit the Entity import...
Can you try with last version of everything ?

**Comment by elkarto** [comment]
It's working fine with [2c99e77d9f](https://github.com/benlbrm/ha-hottoh-component/tree/2c99e77d9f52e7dd97a21537b11e4e295a919562)

![image](https://user-images.githubusercontent.com/36958524/143789569-5be0e9c2-2775-4712-aeb0-584e432bc40f.png)

Thank you!!

**Comment by elkarto** [comment]
I've posted this on hottohpy but I think it's more related to HA component, so I'm moving it here.

Things that I find missing (not very important):
- Water temperature setpoint (Show the current value and be able to change it)
- Status of the pump. (HA component related) 
- Pellet level sensor.

I think the last one is not possible (not exposed by the wifi module), not sure if the first one is available.

Also, the "off" (0 value) for the fan is missing in the climate control. (Only 1-6 can be set) 

However, this is already a huge step forward. Thank you for all your work!!!

**Comment by benlbrm** [comment]
Hello

- Pump Status is exposed as a binary_sensor if available on the stove
- Water temp set point is exposed as an attribute of water temp sensor
- "0" option have been added for the fan speed control
- You can now modify eco, comfort and away temp from integrations panel in HA

**Comment by elkarto** [comment]
**_Pump Status is exposed as a binary_sensor if available on the stove_**

This is not happening for me. There is no binarysensor exposed by the integration. Maybe the "if available" condition is failing?

![image](https://user-images.githubusercontent.com/36958524/143951017-5a6af370-ae66-4385-96b0-2a7c7bf38909.png)


**_Water temp set point is exposed as an attribute of water temp sensor_**

Oh, you are right. I didn't notice it.

**_"0" option have been added for the fan speed control_**

Working fine!

**_You can now modify eco, comfort and away temp from integrations panel in HA_**

Also working!!

**_For the pellet level, it will be difficult for me to find it since it's not available in my stove, what you can do is to try to find it directly on hottohpy lib reading the row values returned by the stove with:_**
`print("Info: %s", stove.client._info) print("Data: %s", stove.client._data) print("Data2: %s", stove.client._data2)`

Perfect. I'll try and see if I have any luck.
