### ISSUE TITLE
"'Hottoh' object has no attribute 'setOn' / 'setOff'" when using the switch entity to power On/Off

### ISSUE THREAD

**Issue by elkarto** [benlbrm/ha-hottoh-component#4]
Hey!! How's it going?

I'm getting this error when I try to turn on/off the stove using the switch entity.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hottoh/switch.py:47
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:27:04 (1 occurrences)
Last logged: 16:27:04

[140253944484960] 'Hottoh' object has no attribute 'setOn'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 948, in async_turn_on
    await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hottoh/switch.py", line 47, in turn_on
    self.api.setOn()
AttributeError: 'Hottoh' object has no attribute 'setOn'
```

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hottoh/switch.py:50
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 16:27:16 (1 occurrences)
Last logged: 16:27:16

[140253944484960] 'Hottoh' object has no attribute 'setOff'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 956, in async_turn_off
    await self.hass.async_add_executor_job(ft.partial(self.turn_off, **kwargs))
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hottoh/switch.py", line 50, in turn_off
    self.api.setOff()
AttributeError: 'Hottoh' object has no attribute 'setOff'
```

It is not a big problem as I can switch on and off from the climate entity without issues.

Since the releases published in HACS, I have not experienced any other issues with the integration and it seems to be quite stable. Good job!!

Thank you and Merry Christmas!

**Comment by benlbrm** [comment]
Hello,
Thanks for your feedback ! This is solved now.
Merry Christmas also to you !
